### PR TITLE
Kubernetes deployments

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@orpiske I'm able to get the worker nodes to connect to the maestro broker with this, and expose it externally in order to use maestro-cli to talk to the broker.

There is an exception in the activemq broker around read-only directories, but that didn't seem to affect startup at least.

Hold on merging it for now, I will do some more testing.

**Comment by orpiske** [comment]
Sure, I will wait for your feedback before merging this. Thanks!

**Comment by orpiske** [comment]
@lulf Can I merge this?

**Comment by lulf** [comment]
@orpiske Yes, it is ready for merge.

**Pull request merged**
